modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/bernie-g/Techarium/issues"
[[mods]]
modId = "techarium"
version = "${file.jarVersion}"
displayName = "Techarium"
displayURL = "https://github.com/bernie-g/Techarium"
authors = "Gecko (Dev) + Drizzs (Dev) + Ycar (Artist)"
description = '''
Techarium is a mod centered around farming tech'''

[[dependencies.techarium]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.techarium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "NONE"
side = "BOTH"
